### ISSUE TITLE
Project TODO List

### ISSUE THREAD

**Issue by edward62740** [edward62740/sc1015-project#1]
# General workflow
- [x] Import and clean data
- [x] EDA to correlate individual stats with fradulence label
- [x] Remove unused columns and append label to boolean values
- [x] Removal of special chars and lemmatization
- [x] TF-IDF feature extraction
- [x] Random forest
- [x] #2
- [x] LSTM
- [x] #11 
- [x] Data-driven insights and conclusion

## Possible issues
- Class imbalance (significantly more real than fake)
- Data inconsistency (salary is sometimes a range, sometimes single value)
